<!DOCTYPE html>
<html lang="en" style="margin:0; padding:0;">
<head>
    
    <meta charset="UTF-8">
    <title>AWB Label</title>
    <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            font-family: sans-serif;
            font-size: 10pt;
        }

        .label-wrapper {
            width: 100%;
            height: 100%;
            box-sizing: border-box;
            padding: 5px;
            border: 1px solid #222;
        }

        .section {
            border-bottom: 1px solid #222;
            padding: 5px 3px;
        }

        .section:last-child {
            border-bottom: none;
        }

        .barcode {
            text-align: center;
            margin-top: 5px;
        }

        .barcode img {
            width: 250px;
            height: 100px;
        }

        .bold {
            font-weight: bold;
        }

        .footer {
            font-size: 8pt;
            text-align: center;
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <div class="label-wrapper">

        <!-- Header using Table (Logo - COD - QR) -->
        <div class="section">
            <table width="100%" style="border-collapse: collapse;">
                <tr>
                    <!-- Left: Logo -->
                    <td style="text-align: left; width: 33%;">
                        <img src="{{ settings()->logo_image }}" alt="rushly" width="100">
                    </td>

                    <!-- Center: COD and Page Info -->
                    <td style="text-align: center; width: 34%;">
                        @if($data['totalPages'] > 1)
                            <div>{{ $data['currentPage'] }} / {{ $data['totalPages'] }}</div>
                        @endif

                        @if($data['isCod'] && $data['codAmount'] > 0)
                            <div class="bold">COD # {{ $data['codAmount'] }}</div>
                        @endif
                    </td>

                    <!-- Right: QR Code -->
                    <td style="text-align: right; width: 33%;">
                        <img src="data:image/png;base64,{{ DNS2D::getBarcodePNG($data['feeriAwb'], 'QRCODE') }}" alt="QR Code" width="60" height="60">
                    </td>
                </tr>
            </table>
        </div>

        <!-- Sender Info -->
        <div class="section">
            <b>{{ __('Sender:') }}</b>
            <div class="bold">{{ $data['sender']['name'] }}</div>
            <div>{{ $data['sender']['addressLine1'] }}</div>
            <div>{{ $data['sender']['country'] }}</div>
            <div>Mobile No: {{ $data['sender']['phone'] }}</div>
        </div>

        <!-- Receiver Info -->
        <div class="section">
            <b>{{ __('Receiver:') }}</b>
            <div class="bold">{{ $data['receiver']['name'] }}</div>
            <div>{{ $data['receiver']['addressLine1'] }} {{ $data['receiver']['addressLine2'] ?? '' }}</div>
            <div>{{ $data['receiver']['city'] }} {{ $data['receiver']['state'] ?? '' }} {{ $data['receiver']['country'] }}</div>
            <div>Mobile No: {{ $data['receiver']['phone'] }}</div>
        </div>

        <!-- Barcode -->
        <div class="section barcode">
            <?php
                $awb = $data['orderNumber'];
                echo '<img src="data:image/png;base64,' . DNS1D::getBarcodePNG($awb, 'C128') . '" alt="barcode" />';
            ?>
            <div>{{ $data['orderNumber'] }}</div>
        </div>

        <!-- Extra Info -->
        <div class="section">
            <div>Date: {{ $data['date'] }}</div>
            <div>Description: {{ $data['description'] }}</div>
            <div>AWB #: {{ $data['awb'] }}</div>
            <div>RUSHLY-AWB #: {{ $data['feeriAwb'] }}</div>

            @if($data['isCod'] && $data['codAmount'] > 0)
                <div class="bold">Grand Total: {{ $data['codAmount'] }} SAR</div>
            @endif
        </div>

        <!-- Footer -->
        <div class="footer">
            Generated by Rushly Express
        </div>

    </div>
</body>
</html>
