<?php

return [
    'label'     => 'Accounting',
    'overview'  => 'Money flow on your account: payments you have received, payouts to your bank, invoices issued to you, and the Saudi ZATCA e-invoicing area.',
    'sub_pages' => [

        'payments-received' => [
            'icon'    => 'Banknote',
            'label'   => 'Payments received',
            'purpose' => 'Inbound payments credited to your account — from card / online gateway, from wallet recharges, and from prepaid customers. Read-only.',
            'pages' => [
                ['path' => 'Index', 'desc' => 'Paginated list with amount, card / source type, transaction reference, originating account and date.'],
            ],
            'fields' => [
                'transaction_id', 'amount', 'card_type', 'from_account', 'received_on',
            ],
            'cross_links' => 'Mirrors entries in Account Transactions under Reports. The same payments are aggregated into Total Summary as "Paid amount".',
            'notes'       => 'Refunds and chargebacks appear as negative-amount rows. The transaction reference is the gateway-provided id — keep it for any dispute.',
        ],

        'payout' => [
            'icon'    => 'Wallet',
            'label'   => 'Payouts to your account',
            'purpose' => 'Outbound transfers from the operator to your bank / wallet — the money the courier collected on your behalf (COD) minus delivery, COD and VAT charges.',
            'pages' => [
                ['path' => 'Request', 'desc' => 'Submit a payout request for the current payable balance. Shows the breakdown before you confirm.'],
                ['path' => 'History', 'desc' => 'List of past payout requests with status (pending, processing, paid, rejected) and the transaction reference once paid.'],
            ],
            'fields' => [
                'requested_amount', 'merchant_account', 'transaction_id',
                'reference_file', 'status', 'processed_on',
            ],
            'status_flow' => [
                ['label' => 'Pending',    'tone' => 'warn'],
                ['label' => 'Processing', 'tone' => 'info'],
                ['label' => 'Paid',       'tone' => 'ok'],
                ['label' => 'Rejected',   'tone' => 'bad'],
            ],
            'cross_links' => 'Driven by your Current payable balance — see the same figure on the Dashboard and on Total Summary.',
            'notes'       => 'You can only request a payout when the current payable is above the operator-set minimum. Multiple requests against the same balance are rejected.',
        ],

        'invoice' => [
            'icon'    => 'Receipt',
            'label'   => 'Invoices',
            'purpose' => 'Generated invoices for the shipments delivered in a billing period. Each invoice rolls up cash collected, delivery charges, VAT and the resulting payable to you.',
            'pages' => [
                ['path' => 'Index',   'desc' => 'List of invoices: invoice id, date, cash collection, total charge, current payable, status.'],
                ['path' => 'Details', 'desc' => 'Line-by-line breakdown for one invoice — every shipment included, its charges and the running total.'],
                ['path' => 'Export',  'desc' => 'Download an invoice as PDF or CSV from the row actions.'],
            ],
            'fields' => [
                'invoice_id', 'invoice_date', 'cash_collection',
                'total_charge', 'current_payable', 'status', 'parcels',
            ],
            'status_flow' => [
                ['label' => 'Unpaid',     'tone' => 'warn'],
                ['label' => 'Processing', 'tone' => 'info'],
                ['label' => 'Paid',       'tone' => 'ok'],
            ],
            'cross_links' => 'Each invoice line is a shipment from Shipments. Marking the invoice Paid moves the corresponding amount into Payments received.',
            'notes'       => 'Invoices are generated by a scheduled job per billing period — typically weekly or monthly depending on your contract. Disputes go through Support.',
        ],

        'zatca-invoices' => [
            'icon'    => 'FileText',
            'label'   => 'ZATCA invoices',
            'purpose' => 'Journal of every Saudi ZATCA-compliant e-invoice issued for your shipments — XML payload, ZATCA UUID, clearance status, and the embedded QR code.',
            'pages' => [
                ['path' => 'Index',     'desc' => 'List of issued e-invoices with date, customer, total, ZATCA UUID, clearance status.'],
                ['path' => 'Details',   'desc' => 'Full invoice payload — line items, VAT breakdown, ZATCA QR code, signed XML, clearance response.'],
                ['path' => 'Retry',     'desc' => 'For invoices stuck at "Clearance failed", retry the submission to ZATCA from the row actions.'],
            ],
            'fields' => [
                'zatca_uuid', 'invoice_hash', 'signed_xml', 'qr_code',
                'clearance_status', 'clearance_response', 'issued_at',
            ],
            'status_flow' => [
                ['label' => 'Pending',          'tone' => 'default'],
                ['label' => 'Cleared',          'tone' => 'ok'],
                ['label' => 'Clearance failed', 'tone' => 'bad'],
            ],
            'cross_links' => 'Each ZATCA invoice references the matching billing invoice under Invoices and the shipments it bills for.',
            'notes'       => 'Required for KSA tenants. ZATCA Phase 2 requires every invoice to be cleared in real time — until it is, the local invoice cannot be considered final.',
        ],

        'zatca-settings' => [
            'icon'    => 'Settings',
            'label'   => 'ZATCA settings',
            'purpose' => 'Configure your VAT registration number and the credentials used to submit invoices to the ZATCA Fatoora portal.',
            'pages' => [
                ['path' => 'Form', 'desc' => 'Company VAT number, CR number, seller name, ZATCA OTP / device CSID, signing certificate.'],
                ['path' => 'Test', 'desc' => 'Send a test invoice to ZATCA sandbox to confirm credentials before going live.'],
            ],
            'fields' => [
                'vat_number', 'cr_number', 'seller_name',
                'device_csid', 'private_key', 'environment',
            ],
            'cross_links' => 'These credentials are used by every entry under ZATCA invoices. If you rotate the device CSID, do it here first.',
            'notes'       => 'Wrong credentials cause every invoice to fail clearance with the same error — test in sandbox first.',
        ],

    ],
];
