<!DOCTYPE html>
<html lang="en" style="margin:0; padding:0;">
<head>
    
    <meta charset="UTF-8">
    <title>AWB Label</title>
    <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            font-family: sans-serif;
            font-size: 10pt;
        }

        .label-wrapper {
            width: 100%;
            height: 100%;
            box-sizing: border-box;
            padding: 5px;
            border: 1px solid #222;
        }

        .section {
            border-bottom: 1px solid #222;
            padding: 5px 3px;
        }

        .section:last-child {
            border-bottom: none;
        }

        .barcode {
            text-align: center;
            margin-top: 5px;
        }

        .barcode img {
            width: 250px;
            height: 100px;
        }

        .bold {
            font-weight: bold;
        }

        .footer {
            font-size: 8pt;
            text-align: center;
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <div class="label-wrapper">

        <!-- Header using Table (Logo - COD - QR) -->
        <div class="section">
            <table width="100%" style="border-collapse: collapse;">
                <tr>
                    <!-- Left: Logo -->
                    <td style="text-align: left; width: 33%;">
                        <img src="{{ asset('assets/img/logos/feeri-logo.png') }}" alt="Rushly Logo" width="100">
                    </td>

                    <!-- Center: COD and Page Info -->
                    <td style="text-align: center; width: 34%;">
                        @if($data['totalPages'] > 1)
                            <div>{{ $data['currentPage'] }} / {{ $data['totalPages'] }}</div>
                        @endif

                        @if($data['isCod'] && $data['codAmount'] > 0)
                            <div class="bold">COD # {{ $data['codAmount'] }}</div>
                        @endif
                    </td>

                    <!-- Right: QR Code -->
                    <td style="text-align: right; width: 33%;">
                        <img src="data:image/png;base64,{{ DNS2D::getBarcodePNG($data['feeriAwb'], 'QRCODE') }}" alt="QR Code" width="60" height="60">
                    </td>
                </tr>
            </table>
        </div>

        <!-- Sender Info -->
        <div class="section">
            <div class="bold">{{ $data['sender']['name'] }}</div>
            <div>{{ $data['sender']['addressLine1'] }}</div>
            <div>{{ $data['sender']['country'] }}</div>
            <div>Mobile No: {{ $data['sender']['phone'] }}</div>
        </div>

        <!-- Receiver Info -->
        <div class="section">
            <div class="bold">{{ $data['receiver']['name'] }}</div>
            <div>{{ $data['receiver']['addressLine1'] }} {{ $data['receiver']['addressLine2'] ?? '' }}</div>
            <div>{{ $data['receiver']['city'] }} {{ $data['receiver']['state'] ?? '' }} {{ $data['receiver']['country'] }}</div>
            <div>Mobile No: {{ $data['receiver']['phone'] }}</div>
        </div>

        <!-- Barcode -->
        <div class="section barcode">
            <?php
                $awb = $data['orderNumber'];
                echo '<img src="data:image/png;base64,' . DNS1D::getBarcodePNG($awb, 'C128') . '" alt="barcode" />';
            ?>
            <div>{{ $data['orderNumber'] }}</div>
        </div>

        <!-- Extra Info -->
        <div class="section">
            <div>Date: {{ $data['date'] }}</div>
            <div>Description: {{ $data['description'] }}</div>
            <div>AWB #: {{ $data['awb'] }}</div>
            <div>FEERI #: {{ $data['feeriAwb'] }}</div>

            @if($data['isCod'] && $data['codAmount'] > 0)
                <div class="bold">Grand Total: {{ $data['codAmount'] }} SAR</div>
            @endif
        </div>

        <!-- Footer -->
        <div class="footer">
            Generated by Rushly Express
        </div>

    </div>
</body>
</html>


<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <link rel="shortcut icon" href="{{ asset('backend/') }}/images/favicon.jpg">
    <style>

        .main-table{
            border:1px dashed;
            padding:2px;
        }
        .label-section {
            width: 7.5cm;
            height: 3.5cm;
        }

        @media print {
            .label-size{
                display: none;
            }
            .main-table{
                border:unset;
                padding:unset;
            }
            *{
                font-size: 10px!important;
            }

            .label-section {
                width: unset;
                height: unset;
            } 
            @page {
                size: 7.5cm 3.5cm;
                margin: 5px !important;
            } 
            body {
                zoom: 100%;
            } 
        }
       
    </style>
</head>

<body>
    <div class="label-size" style="margin-bottom: 5px">
        <span style="color:red">Label size: 7.5cm X 3.5cm</span>
    </div>
    <div class="label-section"> 
        <table width="100%" border="0" cellpadding="0" cellspacing="0" class="main-table">
            <tbody>
                <tr>
                    <td colspan="3" width="100%">
                        <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td style="width:140px;  border-right: 1px solid;padding-right:2px">
                                        <img alt="Logo" src="{{ settings()->logo_image }}" class="logo" style="width:70px">
                                    </td>
                                    <td style="padding-left: 2px;width:100%;">
                                        <b>{{ __('Merchant:') }}</b> {{ $parcel->merchant->business_name }},
                                        {{ $parcel->merchant->address }}, {{ $parcel->merchant->user->mobile }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" >
                            <tbody>
                                <tr>
                                    <td  style="line-height:1.2;width:50%; border-right: 1px solid;border-top:#000000  1px solid;border-bottom:#000000 1px solid; padding:2px;padding-left:0px">
                                        <div><b>{{ __('Customer :') }}</b> {{ $parcel->customer_name }} ,
                                            {{ $parcel->customer_phone }}, {{ $parcel->customer_address }}</div>
                                    </td>   
                                    <td  style="line-height:1.2;width:50%;border-top:#000000  1px solid;border-bottom:#000000 1px solid;padding:2px">
                                        <div  >
                                            <b>Hub</b> :  <span>{{ optional($parcel->hub)->name }}</span><br>
                                            <b>Cash</b> : <span> {{ $parcel->cash_collection }}</span></br>
                                            <b>Route</b> :<span> ISD </span>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr >
                    <td style="text-align:center!important"  >
                        <div style="display: inline-block;margin:auto;margin-top:3px">{!! $parcel->barcodeprint !!}</div>
                        <div>{{ $parcel->tracking_id }}</div>
                    </td>
                </tr>
            </tbody>
        </table> 
    </div>
    
</body>

</html>

  